/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tic.tac.toe;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.InputStream;
import static java.lang.System.exit;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author anmol
 */
public class MultiDifficulty extends javax.swing.JFrame {

    /**
     * Creates new form MultiDifficulty
     */
    public MultiDifficulty() {
        CustomCursor();
        initComponents();
        setSize(900, 600);
        setLocation(225,75);
        EXIT.setOpaque(false);
        EXIT.setContentAreaFilled(false);
        EXIT.setBorderPainted(false);
        GO.setOpaque(false);
        GO.setContentAreaFilled(false);
        GO.setBorderPainted(false);
        HOME.setOpaque(false);
        HOME.setContentAreaFilled(false);
        HOME.setBorderPainted(false);
        setResizable(false);
        setTitle("TIC-TAC-TOE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        GO = new javax.swing.JButton();
        HOME = new javax.swing.JButton();
        player1NameText = new javax.swing.JTextField();
        player2NameText = new javax.swing.JTextField();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tic/tac/toe/multiplayer.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 600);

        GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOActionPerformed(evt);
            }
        });
        jPanel1.add(GO);
        GO.setBounds(517, 487, 110, 70);

        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });
        jPanel1.add(HOME);
        HOME.setBounds(397, 487, 90, 60);

        player1NameText.setBackground(new java.awt.Color(235, 159, 61));
        player1NameText.setFont(new java.awt.Font("Jurassic Park", 0, 48)); // NOI18N
        player1NameText.setForeground(new java.awt.Color(255, 255, 255));
        player1NameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player1NameText.setBorder(null);
        player1NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1NameTextActionPerformed(evt);
            }
        });
        jPanel1.add(player1NameText);
        player1NameText.setBounds(303, 202, 280, 30);

        player2NameText.setBackground(new java.awt.Color(235, 159, 61));
        player2NameText.setFont(new java.awt.Font("Jurassic Park", 0, 48)); // NOI18N
        player2NameText.setForeground(new java.awt.Color(255, 255, 255));
        player2NameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player2NameText.setBorder(null);
        jPanel1.add(player2NameText);
        player2NameText.setBounds(308, 345, 280, 40);

        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT);
        EXIT.setBounds(268, 497, 100, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
        // TODO add your handling code here:
        playturnSound();
        Players player1 = new Players();
        player1.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_HOMEActionPerformed

    String player1Name;
    String player2Name;

    private void GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOActionPerformed
        // TODO add your handling code here:
        playturnSound();
        if(player1NameText.getText().equals("") || player2NameText.getText().equals("")  ){
            JOptionPane.showMessageDialog(null, "Enter the Name of Player");
        }
        else{
            player1Name = player1NameText.getText();
            player2Name = player2NameText.getText();
            
            MultiGame game = new MultiGame(player1Name, player2Name);
          
            game.setVisible(true);
            setVisible(false);
           
        }
        
        
    }//GEN-LAST:event_GOActionPerformed

    private void player1NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1NameTextActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        playturnSound();
        exit(0);
    }//GEN-LAST:event_EXITActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiDifficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiDifficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiDifficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiDifficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiDifficulty().setVisible(true);
            }
        });
    }
    
    
    public void CustomCursor() {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage(getClass().getResource("/tic/tac/toe/cursor.png"));
        Point point = new Point(0,0);
        Cursor cursorR = toolkit.createCustomCursor(img, point, "cursor");
        
        setCursor(cursorR);
    }
    public void playturnSound()
    {
        try
        {
            InputStream inputStream = getClass().getResourceAsStream("/tic/tac/toe/turn.wav");
            AudioStream audioStream = new AudioStream(inputStream);
            AudioPlayer.player.start(audioStream);
        }
        catch (Exception e)
        {
            System.out.println("ERROR");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton GO;
    private javax.swing.JButton HOME;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField player1NameText;
    private javax.swing.JTextField player2NameText;
    // End of variables declaration//GEN-END:variables
}
